import { Inter } from 'next/font/google'
import './globals.css'
import Provider from './context/AuthContext'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ROOM',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Provider>
          {children}
          <Toaster position='top-right'/>
        </Provider>
      </body>
    </html>
  )
}
